### PR TITLE
Create a mozprofile class for managing chrome profiles

### PR DESCRIPTION
**Pull request by ahal**
The first commit is just vendoring in the latest mozprofile/mozrunner copies.
The second commit is the actual mozbase changes.
The third is a simple change to start using these new changes in raptor.

Once this lands I'll start working on getting all the necessary mozrunner/mozprofile changes landed in mozilla-central. I'll add tests for them at that point too.

### CODE REVIEW

**Review by rwood-moz — DISMISSED** [review]

**Comment by rwood-moz** [comment]
Cool! A couple things I noticed after briefly trying out the patch locally with Raptor:

- When Chrome starts up now via Raptor, it is not running in the foreground; the raptor terminal is foreground and Chrome is in the background - that is new behaviour; when running Raptor on Firefox, Firefox is is the active/foreground app

- I notice when Chrome starts the existing tab is a "chrome://welcome/?variant=everywhere" tab; is it possible to make this a pure blank tab instead? Just wondering if that would make browser startup slightly faster, but I don't think it's a big deal although if chrome://welcome is accessing the net then that may not be good for during test runs, especially if it does something in the background during Raptor tests

**Comment by rwood-moz** [comment]
(Maybe those behaviours can be changed via a preferences file, which I can add in Raptor)

**Review by rwood-moz — APPROVED** [review]
Awesome, LGTM

**Comment by ahal** [comment]
Good points.

I'm noticing the welcome page issue too, but I don't think I'm hitting the foreground one. Weird. I bet Chrome is showing us the welcome page because it's the first time we're running with these new profiles. Hopefully there's a pref we can use to turn it off.

We *should* be able to set prefs by creating a file called `chrome.json` in raptor/preferences. I haven't figured out how to check if a pref is set within Chrome itself, but I have verified that things in that file will appear in the `path/to/profile/Preferences` file.

Feel free to merge if you like. Or if you want to hold off while we figure out those issues that's fine too.

**Comment by rwood-moz** [comment]
Thanks! I think we should go ahead and land this, and look into using specific prefs and/or chrome cmd line options later.

**Pull request merged**
