### PR TITLE
Always use up-to-date libraries in the vendor directory

### PR DESCRIPTION
**Pull request by ahal**
This makes it so running 'pip install -r mozbase_requirements.txt' is no
longer necessary. This was a problem because it meant changes to the
vendor directory weren't picked up unless you re-installed the packages
in your virtualenv. Due to pip's caching, this was a pain to do.

Now we simply add the 'vendor' directory to sys.path directly in the
'raptor' module, so we'll pick up changes automatically. W'll need to
remember to remove this when we land in mozilla-central.

### CODE REVIEW

**Review by rwood-moz — DISMISSED** [review]
LGTM thanks Andrew

**Comment by rwood-moz** [comment]
Oh wait, I get an error.

I blew away my raptor-venv. Mada a new virtualenv, did python setup.py develop, and tried to run raptor but get:

(raptor-venv) Roberts-MacBook-Pro-1927:raptor rwood$ raptor -t raptor-firefox-tp7 -b "/Users/rwood/mozilla-unified/obj-x86_64-apple-darwin17.4.0/dist/Nightly.app/Contents/MacOS/firefox"
Traceback (most recent call last):
  File "/Users/rwood/raptor/raptor-venv/bin/raptor", line 11, in <module>
    load_entry_point('raptor', 'console_scripts', 'raptor')()
  File "/Users/rwood/raptor/raptor-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/rwood/raptor/raptor-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/rwood/raptor/raptor-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/rwood/raptor/raptor-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/rwood/raptor/raptor/raptor.py", line 14, in <module>
    from mozlog import commandline, get_default_logger
  File "/Users/rwood/raptor/vendor/mozlog/__init__.py", line 22, in <module>
    from . import unstructured
  File "/Users/rwood/raptor/vendor/mozlog/unstructured/__init__.py", line 9, in <module>
    from .loglistener import LogMessageServer
  File "/Users/rwood/raptor/vendor/mozlog/unstructured/loglistener.py", line 7, in <module>
    from six.moves import socketserver
ImportError: No module named six.moves

**Comment by ahal** [comment]
Ah oops. I think it's because six gets installed when you install pytest (which is also why it's working in travis ci). I'll add it to the setup.py. This will be automatically available in mozilla-central when we merge.

**Comment by rwood-moz** [comment]
Thanks Andrew!

**Pull request merged**
